# softmax_func

In [1]:
a = np.array([0.3,2.9,4.0])

In [2]:
a

array([0.3, 2.9, 4. ])

In [3]:
exp_a = np.exp(a)
exp_a

array([ 1.34985881, 18.17414537, 54.59815003])

In [4]:
sum_exp_a = np.sum(exp_a)
sum_exp_a

74.1221542101633

In [5]:
y = exp_a / sum_exp_a
y

array([0.01821127, 0.24519181, 0.73659691])

In [6]:
def softmax(a):
    exp_a = np.exp(a)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    return y

In [7]:
softmax(a)

array([0.01821127, 0.24519181, 0.73659691])