In [4]:
import numpy as np

In [5]:
X = np.array([1.0, 0.5])
W1 = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
B1 = np.array([0.1, 0.2, 0.3])

In [7]:
print(W1.shape)

(2, 3)


In [9]:
A1 = np.dot(X,W1) + B1
A1

array([0.3, 0.7, 1.1])

In [10]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [11]:
Z1 = sigmoid(A1)
Z1

array([0.57444252, 0.66818777, 0.75026011])

In [12]:
W2 = np.array([[0.1,0.4], [0.2, 0.5], [0.3, 0.6]])
B2 = np.array([0.1, 0.2])

In [13]:
A2 = np.dot(Z1,W2) + B2
A2

array([0.51615984, 1.21402696])

In [14]:
Z2 = sigmoid(A2)
Z2

array([0.62624937, 0.7710107 ])

In [16]:
def identity_function(x):
    return x

In [17]:
W3 = np.array([[0.1, 0.3], [0.2, 0.4]])
B3 = np.array([0.1, 0.2])

In [18]:
A3 = np.dot(Z2, W3) + B3

In [19]:
A3

array([0.31682708, 0.69627909])

In [21]:
Y = identity_function(A3) # Y = A3 恒等関数

# まとめ

In [22]:
def init_network():
    network = {}
    network['W1'] = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
    network['b1'] = np.array([0.1, 0.2, 0.3])
    network['W2'] = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
    network['b2'] = np.array([0.1, 0.2])
    network['W3'] = np.array([[0.1, 0.3], [0.2, 0.4]])
    network['b3'] = np.array([0.1, 0.2])
    return network
def forward(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']
    a1 = np.dot(x, W1) + b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2, W3) + b3
    y = identity_function(a3)
    return y
network = init_network()
x = np.array([1.0, 0.5])
y = forward(network, x)
print(y) # [ 0.31682708 0.69627909

[0.31682708 0.69627909]
