# softmax_func

In [1]:
import numpy as np

In [2]:
a = np.array([0.3,2.9,4.0])

In [3]:
a

array([0.3, 2.9, 4. ])

In [4]:
exp_a = np.exp(a)
exp_a

array([ 1.34985881, 18.17414537, 54.59815003])

In [5]:
sum_exp_a = np.sum(exp_a)
sum_exp_a

74.1221542101633

In [6]:
y = exp_a / sum_exp_a
y

array([0.01821127, 0.24519181, 0.73659691])

In [7]:
def softmax(a):
    exp_a = np.exp(a)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    return y

In [8]:
softmax(a)

array([0.01821127, 0.24519181, 0.73659691])

In [9]:
# for overflow
def softmax_(a):
    max_a = np.max(a)
    b = a - max_a
    exp_b = np.exp(b)
    sum_exp_b = np.sum(exp_b)
    y = exp_b/sum_exp_b
    return y

In [10]:
_ = np.array([1010, 1000, 990])

In [11]:
softmax(_)

C:\Users\jin\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in true_divide
  after removing the cwd from sys.path.


array([nan, nan, nan])

In [13]:
softmax_(_)

array([9.99954600e-01, 4.53978686e-05, 2.06106005e-09])

In [14]:
# 3.5.3

In [16]:
a = np.array([0.3, 2.9, 4.0])
y = softmax_(a)
y

array([0.01821127, 0.24519181, 0.73659691])

In [18]:
np.sum(y)

1.0